Settings:
  Verbose: false
Listeners:
  TinyListeners:
    Display-Unriding: false
    Item-Consume-Update-Inventory: false
Locale:
  Console: en_us
  Default-To: {}
WeaponMechanics:
  Actionbar-Weapon-Info-Display: false