name: BlobLib
version: ${project.parent.version}
main: us.mytheria.bloblib.BlobLib
api-version: 1.17
load: STARTUP
loadbefore: [ Vault, WorldGuard, WorldEdit, LibsDisguises, ProtocolLib ]
authors: [ promorrom, j0ach1mmall3, Dean B, FourteenBrush, SmallCode ]
commands:
  bloblib:
    usage: "/bloblib reload"