name: BlobLib
version: ${project.version}
main: us.mytheria.bloblib.BlobLib
api-version: 1.16
load: STARTUP
softdepend: [ WorldGuard, WorldEdit, Vault ]
authors: [ promorrom, j0ach1mmall3, Dean B, FourteenBrush, SmallCode ]
commands:
  bloblib:
    usage: "/bloblib reload"