name: BlobLib
version: 1.698.32
main: io.github.anjoismysign.bloblib.BlobLib
api-version: 1.21.5
load: STARTUP
loadbefore:
  - Skript
  - Vault
  - LibsDisguises
  - ProtocolLib
  - WorldEdit
  - WorldGuard
  - WeaponMechanics
  - ItemsAdder
  - BlobTycoon
  - AlternativeSaving
authors: [ anjoismysign ]
commands:
  bloblib:
    usage: "/bloblib reload"
libraries:
  - commons-io:commons-io:2.7
  - org.mongodb:mongodb-driver-sync:4.10.2
  - net.lingala.zip4j:zip4j:2.11.5
  - org.apache.commons:commons-lang3:3.17.0
  - io.github.classgraph:classgraph:4.8.157